services:
  backup:
    image: ghcr.io/iemarjay/pg-r2-backup:latest
    restart: unless-stopped
    env_file:
      - .env.backup
    healthcheck:
      test: ["/app/scripts/healthcheck.sh"]
      interval: 6h
      timeout: 5s
      retries: 1
    depends_on:
      - postgres
